// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XcaUXYWWyELW4MvHaB4qOPGoaF2Tsa4',
    appId: '1:326452444434:web:0068a2c24711356068c7cb',
    messagingSenderId: '326452444434',
    projectId: 'haajir1-test-20261777',
    authDomain: 'haajir1-test-20261777.firebaseapp.com',
    storageBucket: 'haajir1-test-20261777.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASMTpY_WqyJM7-6kpJDukPyO0iEUZ3JgM',
    appId: '1:326452444434:android:2f21c2ff38870b8c68c7cb',
    messagingSenderId: '326452444434',
    projectId: 'haajir1-test-20261777',
    storageBucket: 'haajir1-test-20261777.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyflLiKK-fzXfr4M3KUdtnczuj-y42peI',
    appId: '1:326452444434:ios:968ca37bf7945dbe68c7cb',
    messagingSenderId: '326452444434',
    projectId: 'haajir1-test-20261777',
    storageBucket: 'haajir1-test-20261777.firebasestorage.app',
    iosClientId: '326452444434-c99g22l968icft5si6tthqpr7ct3erph.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyflLiKK-fzXfr4M3KUdtnczuj-y42peI',
    appId: '1:326452444434:ios:968ca37bf7945dbe68c7cb',
    messagingSenderId: '326452444434',
    projectId: 'haajir1-test-20261777',
    storageBucket: 'haajir1-test-20261777.firebasestorage.app',
    iosClientId: '326452444434-c99g22l968icft5si6tthqpr7ct3erph.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XcaUXYWWyELW4MvHaB4qOPGoaF2Tsa4',
    appId: '1:326452444434:web:2c28352f83d5685f68c7cb',
    messagingSenderId: '326452444434',
    projectId: 'haajir1-test-20261777',
    authDomain: 'haajir1-test-20261777.firebaseapp.com',
    storageBucket: 'haajir1-test-20261777.firebasestorage.app',
  );
}
